// Referral reason options (shared with specialist platform)
export const SPECIALIST_REASON_OPTIONS: Record<string, string[]> = {
  Endodontist: [
    'Root Canal Treatment',
    'Retreatment',
    'Evaluation Only',
    'Pain Evaluation',
    'Swelling / Abscess',
    'Cracked Tooth Evaluation',
    'Trauma',
  ],
  'Oral & Maxillofacial Surgeon': [
    'Tooth Extraction',
    'Surgical Extraction',
    'Third Molar Evaluation',
    'Implant Placement',
    'Bone Grafting',
    'Pathology / Biopsy',
    'Exposure & Bonding',
    'TMJ Evaluation',
  ],
  Periodontist: [
    'Periodontal Evaluation',
    'Scaling & Root Planing',
    'Gingival Grafting',
    'Osseous Surgery',
    'Crown Lengthening',
    'Implant Placement',
    'Peri-Implantitis Treatment',
  ],
  Prosthodontist: [
    'Full Mouth Rehabilitation',
    'Implant-Supported Prosthesis',
    'Complex Crown & Bridge',
    'Occlusal Reconstruction',
    'Esthetic Consultation',
    'Denture / Overdenture',
  ],
  Orthodontist: [
    'Orthodontic Evaluation',
    'Comprehensive Treatment',
    'Limited Treatment',
    'Clear Aligners',
    'Interceptive Orthodontics',
    'Surgical Orthodontics',
  ],
  'Pediatric Dentist': [
    'Pediatric Dental Evaluation',
    'Caries Management',
    'Pulp Therapy',
    'Extractions',
    'Space Maintainer',
    'Sedation / GA',
    'Behavior Management',
  ],
  'Oral Medicine / Pathology': [
    'Oral Lesion Evaluation',
    'Biopsy',
    'TMJ Disorder',
    'Orofacial Pain',
    'Mucosal Disease',
    'Burning Mouth Syndrome',
  ],
}

export const DEFAULT_REFERRAL_REASONS = [
  'Pain Evaluation',
  'Extraction',
  'Implant Evaluation',
  'Sinus Lift',
  'Evaluation of Lesion',
  'Panoramic X-Ray',
  'Third Molar Evaluation',
  'Third Molar Extraction',
]
